#!/bin/bash
set -e

# Load .env variables if .env file exists
if [ -f .env ]; then
  export $(grep -v '^#' .env | xargs)
fi

# Create folders if they don't exist
mkdir -p src
mkdir -p public

echo "Generating env.ts and env.js..."

# Use default values if not set
GEMINI_API_KEY_VALUE="${API_KEY:='YOUR_GEMINI_API_KEY_NOT_SET'}"
YOUTUBE_API_KEY_VALUE="${YOUTUBE_API_KEY:='YOUR_YOUTUBE_API_KEY_NOT_SET'}"

# Generate TypeScript version
cat > src/env.ts <<EOL
// Auto-generated by build.sh
export const API_KEY = "${GEMINI_API_KEY_VALUE}";
export const YOUTUBE_API_KEY = "${YOUTUBE_API_KEY_VALUE}";
EOL

# Generate JavaScript version for browser use
cat > public/env.js <<EOL
// Auto-generated by build.sh
export const API_KEY = "${GEMINI_API_KEY_VALUE}";
export const YOUTUBE_API_KEY = "${YOUTUBE_API_KEY_VALUE}";
EOL

echo "✅ env.ts generated:"
cat src/env.ts

echo ""
echo "✅ env.js generated:"
cat public/env.js
