// This is a placeholder file.
// It will be overwritten by build.sh during the Vercel build process
// with actual API keys from environment variables.
// Do not edit this file manually if you expect build.sh to manage it.

export const window.API_KEY = 'YOUR_GEMINI_API_KEY_NOT_SET';
export const window.YOUTUBE_API_KEY = 'YOUR_YOUTUBE_API_KEY_NOT_SET';

// console.log("Placeholder env.ts loaded. If you see this in a Vercel deployment, build.sh might not have run correctly.");
